# Generated by Django 4.0.3 on 2022-03-22 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_remove_posts_teste'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Posts',
            new_name='Curso',
        ),
    ]
