# Generated by Django 4.0.3 on 2022-03-26 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0005_imagem_curso_imagens'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='textbox',
            field=models.CharField(default=1, max_length=2000),
            preserve_default=False,
        ),
    ]
