# Generated by Django 4.0.3 on 2022-03-26 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0006_curso_textbox'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='descricao',
            field=models.TextField(max_length=150),
        ),
        migrations.AlterField(
            model_name='curso',
            name='sobre',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='curso',
            name='textbox',
            field=models.TextField(max_length=2000),
        ),
    ]
