# Generated by Django 4.0.3 on 2022-03-22 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0002_imagem_produto_imagens'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='imagens',
        ),
        migrations.AddField(
            model_name='produto',
            name='imagens',
            field=models.ImageField(default=2, upload_to='img'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Imagem',
        ),
    ]
